### ISSUE TITLE
Better error message when props table can't find source.

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-dev-site#252]
# Feature Request

## Description
Props table can only be generated when a non transpiled file can be found. We automatically look for the non-transpiled file even if the consumer provides the lib file, but we fail to warn in a clear way.

We should warn with something like this:
`A non transpiled source file is required for the props table to be generated.`

## Additional Context / Screenshots
The error currently looks like this.
```
ERROR in ./node_modules/thing-js/lib/thing/components/ThingApplication.js?dev-site-props-table
Module build failed (from ./node_modules/terra-dev-site/config/webpack/loaders/devSitePropsTable.js):
Error: Can't resolve '/source/ui/node_modules/thing-js/src/thing/components/ThingApplication' in ''
    at doResolve (/source/ui/node_modules/enhanced-resolve/lib/Resolver.js:209:21)
    at hook.callAsync (/source/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/source/ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/source/ui/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/source/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/source/ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/source/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn1 (eval at create (/source/ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/source/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn43 (eval at create (/source/ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/source/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/source/ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/source/ui/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/source/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn2 (eval at create (/source/ui/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/source/ui/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
 @ ./node_modules/thing-js/lib/terra-dev-site/doc/thing/Thing.1.doc.mdx 12:0-83 165:14-20
 @ ./dev-site-config/build/contentConfig.js
 @ ./dev-site-config/build/siteConfig.js
 @ ./node_modules/terra-dev-site/lib/TerraDevSite.js
```

**Comment by mjhenkes** [comment]
This one is kind of tricky to reproduce in terra-dev-site. The point here is to have a lib file that does not have a src file equivalent. 
Steps to reproduce in terra-dev-site:
1. ensure `terra-dev-site/lib/terra-dev-site/test/loaders/PropsTableExample.js` exists
2. rename `terra-dev-site/src/terra-dev-site/test/loaders/PropsTableExample.jsx` to `terra-dev-site/src/terra-dev-site/test/loaders/PropsTableExample2.jsx` (do not comple again).
3. In `/Users/mh015940/source/terra-dev-site/src/terra-dev-site/test/loaders/propsTable.test.mdx` change the import statement to `import PropsTable from 'terra-dev-site/lib/terra-dev-site/test/loaders/PropsTableExample?dev-site-props-table';`
4. Run `npm run compile:prod`

So in short we make sure a transpiled react class exists in lib, we ensure that it's un-transpiled counterpart cannot be found. We change the import for the class to look at the lib file instead of looking relative to itself, then we run webpack to build the app for prod.

The props table loader requires a non transpiled file to be able to generate the props table, this can be very confusing because sometimes when pulling documentation from npm packages, the src files are not included in the package.

This is the props table loader and error that gets thrown if the file cannot be found.
https://github.com/cerner/terra-dev-site/blob/master/config/webpack/loaders/devSitePropsTable.js#L128

It looks like a general cannot resolve error but we should be more specific and let consumers know that a src file is require to be found for the props table loader to function.

We may be able to write a unit test for this, but it may not be worth the effort.
